import { Product } from '../types';

export const CSV_CAKE_PRODUCTS: Product[] = [
  {
    id: 'prod-6600',
    sku: 'CCTC',
    name: 'Choco Chip Truffle Cake',
    slug: 'choco-chip-truffle-cake',
    shortDescription: 'Rich dark chocolate truffle cake generously coated with crispy semi-sweet chocolate chips and decadent chocolate curls.',
    description: '<p>Our #1 signature bestseller! Baked with layered Dutch dark cocoa sponge, silky chocolate ganache, and studded throughout with premium Belgian chocolate chips.</p>',
    category: 'chocolate',
    subCategory: 'dark-truffle',
    categories: ['chocolate', 'birthday', 'eggless'],
    subcategories: ['dark-truffle', 'chocolate'],
    tags: ['Choco Chip Cake', 'Truffle Cake', 'Chocolate Truffle', 'Birthday Cake', 'Eggless Chocolate'],
    flavours: ['Dark Chocolate Ganache', 'Dutch Cocoa Sponge'],
    eggless: true,
    weightOptions: [
      { label: '0.5 Kg', weightKg: 0.5, price: 499, mrp: 599, isDefault: true },
      { label: '1.0 Kg', weightKg: 1.0, price: 949, mrp: 1199 },
      { label: '1.5 Kg', weightKg: 1.5, price: 1399, mrp: 1799 },
      { label: '2.0 Kg', weightKg: 2.0, price: 1849, mrp: 2399 },
      { label: '3.0 Kg (2-Tier)', weightKg: 3.0, price: 2799, mrp: 3599 },
    ],
    images: [
      { id: 'img-6600-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Choco-Chip-Truffle-Cake.png', isPrimary: true, altText: 'Choco Chip Truffle Cake' },
    ],
    rating: 4.9,
    reviewCount: 142,
    stock: 50,
    stockStatus: 'in_stock',
    badges: ['Bestseller', '100% Eggless', 'Chef Choice'],
    published: true,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'prod-6601',
    sku: 'BCC',
    name: 'Belgian Chocolate Cake',
    slug: 'belgian-chocolate-cake',
    shortDescription: 'Silky smooth 70% pure Callebaut Belgian chocolate ganache poured over tender cocoa sponge.',
    description: '<p>Pure gourmet luxury. Infused with imported single-origin Belgian cocoa and topped with hand-crafted tempered chocolate shards.</p>',
    category: 'chocolate',
    subCategory: 'belgian-chocolate',
    categories: ['chocolate', 'anniversary', 'birthday', 'eggless'],
    subcategories: ['belgian-chocolate', 'dark-truffle'],
    tags: ['Belgian Chocolate', 'Gourmet Cake', 'Callebaut', 'Anniversary Cake'],
    flavours: ['70% Dark Belgian Chocolate', 'Silky Ganache'],
    eggless: true,
    weightOptions: [
      { label: '0.5 Kg', weightKg: 0.5, price: 549, mrp: 699, isDefault: true },
      { label: '1.0 Kg', weightKg: 1.0, price: 1049, mrp: 1299 },
      { label: '1.5 Kg', weightKg: 1.5, price: 1549, mrp: 1949 },
      { label: '2.0 Kg', weightKg: 2.0, price: 1999, mrp: 2599 },
    ],
    images: [
      { id: 'img-6601-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Belgian-Chocolate-Cake.png', isPrimary: true, altText: 'Belgian Chocolate Cake' },
    ],
    rating: 5.0,
    reviewCount: 98,
    stock: 45,
    stockStatus: 'in_stock',
    badges: ['70% Belgian Cocoa', '100% Eggless', 'Premium'],
    published: true,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'prod-6602',
    sku: 'KDC',
    name: 'Kunafa Dubai Cake',
    slug: 'kunafa-dubai-cake',
    shortDescription: 'Viral Dubai-inspired sensation: crispy golden toasted kataifi phyllo, premium Sicilian pistachio cream, and Belgian dark chocolate ganache.',
    description: '<p>The global viral delicacy brought to your doorstep! Crunchy roasted kunafa threads folded with nutty, velvety pistachio butter cream enclosed in smooth chocolate ganache.</p>',
    category: 'trending-cakes',
    subCategory: 'dubai-kunafa',
    categories: ['trending-cakes', 'chocolate', 'birthday'],
    subcategories: ['dubai-kunafa'],
    tags: ['Kunafa Cake', 'Dubai Chocolate', 'Pistachio Kunafa', 'Viral Cake', 'Trending'],
    flavours: ['Pistachio Cream', 'Kataifi Crunch', 'Belgian Chocolate'],
    eggless: true,
    weightOptions: [
      { label: '0.5 Kg', weightKg: 0.5, price: 649, mrp: 799, isDefault: true },
      { label: '1.0 Kg', weightKg: 1.0, price: 1249, mrp: 1499 },
      { label: '1.5 Kg', weightKg: 1.5, price: 1799, mrp: 2199 },
    ],
    images: [
      { id: 'img-6602-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Kunafa-Dubai-Cake.png', isPrimary: true, altText: 'Kunafa Dubai Cake' },
    ],
    rating: 5.0,
    reviewCount: 165,
    stock: 35,
    stockStatus: 'in_stock',
    badges: ['Viral Sensation', 'Dubai Special', 'Trending #1'],
    published: true,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'prod-6603',
    sku: 'CMCC',
    name: 'Classic Mango Cream Cake',
    slug: 'classic-mango-cream-cake',
    shortDescription: 'Seasonal Ratnagiri Alphonso mango pulp infused into light vanilla sponge and fresh mango glaze.',
    description: '<p>Celebrate summer with every bite! Layered with chunks of fresh Alphonso mangoes and light airy whipped cream.</p>',
    category: 'mango-cakes',
    subCategory: 'alphonso-mango',
    categories: ['mango-cakes', 'fruit-cakes', 'birthday', 'eggless'],
    subcategories: ['alphonso-mango'],
    tags: ['Mango Cake', 'Alphonso Mango', 'Fresh Fruit Cake', 'Summer Special'],
    flavours: ['Ratnagiri Alphonso Mango', 'Whipped Vanilla Cream'],
    eggless: true,
    weightOptions: [
      { label: '0.5 Kg', weightKg: 0.5, price: 479, mrp: 599, isDefault: true },
      { label: '1.0 Kg', weightKg: 1.0, price: 899, mrp: 1149 },
      { label: '1.5 Kg', weightKg: 1.5, price: 1349, mrp: 1699 },
    ],
    images: [
      { id: 'img-6603-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/08/Classic-Mango-cream-cake.png', isPrimary: true, altText: 'Classic Mango Cream Cake' },
    ],
    rating: 4.9,
    reviewCount: 88,
    stock: 40,
    stockStatus: 'in_stock',
    badges: ['Seasonal Special', '100% Real Alphonso'],
    published: true,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prod-6604',
    sku: 'PAC',
    name: 'Pineapple Cake',
    slug: 'pineapple-cake',
    shortDescription: 'Juicy tropical pineapple pieces with light vanilla sponge, fresh cherries, and non-dairy whipped cream.',
    description: '<p>A timeless family favourite. Refreshing pineapple compote paired with moist sponge and crowned with maraschino cherries.</p>',
    category: 'fruit-cakes',
    subCategory: 'pineapple',
    categories: ['fruit-cakes', 'birthday', 'eggless'],
    subcategories: ['pineapple'],
    tags: ['Pineapple Cake', 'Fresh Fruit', 'Birthday Cake', 'Eggless'],
    flavours: ['Juicy Pineapple', 'Vanilla Whipped Cream'],
    eggless: true,
    weightOptions: [
      { label: '0.5 Kg', weightKg: 0.5, price: 429, mrp: 529, isDefault: true },
      { label: '1.0 Kg', weightKg: 1.0, price: 799, mrp: 999 },
      { label: '1.5 Kg', weightKg: 1.5, price: 1199, mrp: 1499 },
      { label: '2.0 Kg', weightKg: 2.0, price: 1549, mrp: 1999 },
    ],
    images: [
      { id: 'img-6604-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Pineapple-Cake.png', isPrimary: true, altText: 'Pineapple Cake' },
    ],
    rating: 4.8,
    reviewCount: 110,
    stock: 60,
    stockStatus: 'in_stock',
    badges: ['Fresh Fruit', '100% Eggless'],
    published: true,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'prod-6605',
    sku: 'HLCC',
    name: 'Hearts Of Love Chocolate Cake',
    slug: 'hearts-of-love-chocolate-cake',
    shortDescription: 'Romantic heart-shaped rich chocolate ganache cake crowned with handmade sugar hearts and red rose accents.',
    description: '<p>The quintessential celebration for anniversaries and Valentine’s Day. Express heartfelt love with smooth dark cocoa layers.</p>',
    category: 'anniversary',
    subCategory: 'heart-shaped',
    categories: ['anniversary', 'chocolate', 'birthday'],
    subcategories: ['heart-shaped', 'chocolate'],
    tags: ['Heart Cake', 'Anniversary Cake', 'Romantic Cake', 'Love Cake', 'Chocolate Heart'],
    flavours: ['Dark Chocolate Ganache', 'Ruby Sugar Hearts'],
    eggless: true,
    weightOptions: [
      { label: '0.5 Kg', weightKg: 0.5, price: 549, mrp: 699, isDefault: true },
      { label: '1.0 Kg', weightKg: 1.0, price: 1049, mrp: 1299 },
      { label: '1.5 Kg', weightKg: 1.5, price: 1549, mrp: 1899 },
    ],
    images: [
      { id: 'img-6605-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Hearts-Of-Love-Chocolate-Cake.png', isPrimary: true, altText: 'Hearts Of Love Chocolate Cake' },
    ],
    rating: 4.9,
    reviewCount: 93,
    stock: 45,
    stockStatus: 'in_stock',
    badges: ['Heart Shaped', 'Anniversary Special'],
    published: true,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'prod-6606',
    sku: 'BFC',
    name: 'Black Forest Royal Cake',
    slug: 'black-forest-royal-cake',
    shortDescription: 'Classic German black forest cake with kirsch-infused cocoa sponge, whipped cream, and chocolate flakes.',
    description: '<p>Traditional black forest cake loaded with sour cherry compote, dark chocolate shavings, and maraschino cherries.</p>',
    category: 'birthday',
    subCategory: 'chocolate',
    categories: ['birthday', 'chocolate', 'eggless'],
    subcategories: ['chocolate'],
    tags: ['Black Forest Cake', 'Cherry Cake', 'Birthday Classic', 'Chocolate Shavings'],
    flavours: ['Dark Chocolate Shavings', 'Sour Cherry', 'Whipped Cream'],
    eggless: true,
    weightOptions: [
      { label: '0.5 Kg', weightKg: 0.5, price: 449, mrp: 549, isDefault: true },
      { label: '1.0 Kg', weightKg: 1.0, price: 849, mrp: 1099 },
      { label: '1.5 Kg', weightKg: 1.5, price: 1249, mrp: 1599 },
    ],
    images: [
      { id: 'img-6606-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Choco-Chip-Truffle-Cake.png', isPrimary: true, altText: 'Black Forest Royal Cake' },
    ],
    rating: 4.8,
    reviewCount: 76,
    stock: 55,
    stockStatus: 'in_stock',
    badges: ['Classic Favorite', '100% Eggless'],
    published: true,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'prod-6607',
    sku: 'BSC',
    name: 'Butterscotch Crunch Cake',
    slug: 'butterscotch-crunch-cake',
    shortDescription: 'Golden butterscotch sponge layered with caramel sauce and crunchy handmade cashew praline chunks.',
    description: '<p>Sweet, caramelized, and delightfully crunchy! Topped with butterscotch chips and caramel drizzle.</p>',
    category: 'birthday',
    subCategory: 'butterscotch',
    categories: ['birthday', 'eggless'],
    subcategories: ['butterscotch'],
    tags: ['Butterscotch Cake', 'Praline Crunch', 'Caramel Cake', 'Birthday Special'],
    flavours: ['Butterscotch Caramel', 'Cashew Praline Crunch'],
    eggless: true,
    weightOptions: [
      { label: '0.5 Kg', weightKg: 0.5, price: 449, mrp: 549, isDefault: true },
      { label: '1.0 Kg', weightKg: 1.0, price: 849, mrp: 1099 },
      { label: '1.5 Kg', weightKg: 1.5, price: 1249, mrp: 1599 },
    ],
    images: [
      { id: 'img-6607-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Butterscotch-Pastry01.webp', isPrimary: true, altText: 'Butterscotch Crunch Cake' },
    ],
    rating: 4.7,
    reviewCount: 82,
    stock: 50,
    stockStatus: 'in_stock',
    badges: ['Praline Crunch', '100% Eggless'],
    published: true,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'prod-6608',
    sku: 'RVC',
    name: 'Red Velvet Cream Cheese Heart Cake',
    slug: 'red-velvet-cream-cheese-heart-cake',
    shortDescription: 'Crimson red velvet sponge paired with velvety cream cheese frosting and red sponge dust.',
    description: '<p>Tender, velvety, and luxurious. Crafted with real Philadelphia cream cheese and a subtle cocoa crumb.</p>',
    category: 'anniversary',
    subCategory: 'red-velvet',
    categories: ['anniversary', 'birthday', 'eggless'],
    subcategories: ['red-velvet', 'heart-shaped'],
    tags: ['Red Velvet Cake', 'Cream Cheese', 'Anniversary Cake', 'Heart Cake'],
    flavours: ['Red Velvet Cocoa', 'Philadelphia Cream Cheese'],
    eggless: true,
    weightOptions: [
      { label: '0.5 Kg', weightKg: 0.5, price: 549, mrp: 699, isDefault: true },
      { label: '1.0 Kg', weightKg: 1.0, price: 1049, mrp: 1299 },
      { label: '1.5 Kg', weightKg: 1.5, price: 1549, mrp: 1899 },
    ],
    images: [
      { id: 'img-6608-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Red-Velvet-Pastry01.webp', isPrimary: true, altText: 'Red Velvet Cream Cheese Heart Cake' },
    ],
    rating: 4.9,
    reviewCount: 95,
    stock: 40,
    stockStatus: 'in_stock',
    badges: ['Cream Cheese', 'Anniversary Top Pick'],
    published: true,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'prod-6609',
    sku: 'ETC',
    name: 'Eggless Tiramisu Coffee Cake',
    slug: 'eggless-tiramisu-coffee-cake',
    shortDescription: 'Espresso-soaked sponge layered with whipped mascarpone cream and dusted with dark cocoa powder.',
    description: '<p>The beloved Italian dessert perfected without eggs! Rich aromatic espresso coffee paired with luscious mascarpone cheese.</p>',
    category: 'eggless',
    subCategory: 'tiramisu',
    categories: ['eggless', 'desserts', 'birthday'],
    subcategories: ['tiramisu'],
    tags: ['Tiramisu Cake', 'Coffee Cake', 'Espresso Cake', 'Mascarpone', '100% Eggless'],
    flavours: ['Espresso Coffee', 'Mascarpone Cream'],
    eggless: true,
    weightOptions: [
      { label: '0.5 Kg', weightKg: 0.5, price: 599, mrp: 749, isDefault: true },
      { label: '1.0 Kg', weightKg: 1.0, price: 1149, mrp: 1399 },
    ],
    images: [
      { id: 'img-6609-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Eggless-Tiramisu-Cake.png', isPrimary: true, altText: 'Eggless Tiramisu Coffee Cake' },
    ],
    rating: 4.9,
    reviewCount: 68,
    stock: 35,
    stockStatus: 'in_stock',
    badges: ['Italian Coffee', '100% Eggless'],
    published: true,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
  {
    id: 'prod-6610',
    sku: 'BME',
    name: 'Best Mom Ever Chocolate Cake',
    slug: 'best-mom-ever-chocolate-cake',
    shortDescription: 'Sweet tribute cake with handcrafted edible fondant flowers, gold dusting, and silky chocolate ganache.',
    description: '<p>Celebrate the world’s best Mom on Mother’s Day or her birthday with this heartfelt artisan cake.</p>',
    category: 'by-relation',
    subCategory: 'for-mother',
    categories: ['by-relation', 'chocolate', 'birthday'],
    subcategories: ['for-mother'],
    tags: ['Mom Cake', 'Mother Birthday', 'Mothers Day Cake', 'Chocolate Cake'],
    flavours: ['Dark Chocolate Truffle', 'Sugar Floral'],
    eggless: true,
    weightOptions: [
      { label: '0.5 Kg', weightKg: 0.5, price: 599, mrp: 749, isDefault: true },
      { label: '1.0 Kg', weightKg: 1.0, price: 1099, mrp: 1349 },
    ],
    images: [
      { id: 'img-6610-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Best-Mom-Ever-Chocolate-Cake.png', isPrimary: true, altText: 'Best Mom Ever Chocolate Cake' },
    ],
    rating: 5.0,
    reviewCount: 77,
    stock: 40,
    stockStatus: 'in_stock',
    badges: ['For Mother', 'Heartfelt Gift'],
    published: true,
    createdAt: '2026-05-01T10:00:00Z',
    updatedAt: '2026-05-01T10:00:00Z',
  },
];
