import { Product } from '../types';

export const CSV_DESSERT_PRODUCTS: Product[] = [
  {
    id: 'prod-6762',
    sku: 'CTP',
    name: 'Chocolate Truffle Pastry',
    slug: 'chocolate-truffle-pastry',
    shortDescription: 'Rich, moist chocolate sponge layered with smooth dark chocolate ganache and chocolate curls.',
    description: '<p>A classic individual slice of our bestselling chocolate truffle cake. Perfectly portioned for quick cravings and party boxes.</p>',
    category: 'desserts',
    subCategory: 'pastries',
    categories: ['desserts', 'chocolate'],
    subcategories: ['pastries'],
    tags: ['Chocolate Pastry', 'Truffle Pastry', 'Pastries', 'Desserts'],
    flavours: ['Dark Chocolate Ganache', 'Cocoa Sponge'],
    eggless: true,
    weightOptions: [
      { label: '1 piece', weightKg: 0.1, price: 99, mrp: 120, isDefault: true },
      { label: '2 pieces (Pack of 2)', weightKg: 0.2, price: 189, mrp: 240 },
      { label: '4 pieces (Party Box)', weightKg: 0.4, price: 389, mrp: 480 },
      { label: '6 pieces (Family Box)', weightKg: 0.6, price: 549, mrp: 720 },
      { label: '12 pieces (Celebration Box)', weightKg: 1.2, price: 999, mrp: 1440 },
    ],
    images: [
      { id: 'img-6762-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Chocolate-Truffle-Pastry02.webp', isPrimary: true, altText: 'Chocolate Truffle Pastry' },
      { id: 'img-6762-2', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Chocolate-Truffle-Pastry01.webp', isPrimary: false, altText: 'Chocolate Truffle Pastry Pack' },
    ],
    rating: 4.8,
    reviewCount: 65,
    stock: 80,
    stockStatus: 'in_stock',
    badges: ['Top Pastry', '100% Eggless'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6768',
    sku: 'PP',
    name: 'Pineapple Pastry',
    slug: 'pineapple-pastry',
    shortDescription: 'Fluffy vanilla sponge filled with juicy pineapple crush and dairy whipped cream.',
    description: '<p>Light, refreshing, and full of natural pineapple chunks. An all-time favorite tea-time and dessert treat.</p>',
    category: 'desserts',
    subCategory: 'pastries',
    categories: ['desserts', 'fruit-cakes'],
    subcategories: ['pastries'],
    tags: ['Pineapple Pastry', 'Fruit Pastry', 'Pastries', 'Desserts'],
    flavours: ['Juicy Pineapple', 'Whipped Cream'],
    eggless: true,
    weightOptions: [
      { label: '1 piece', weightKg: 0.1, price: 99, mrp: 120, isDefault: true },
      { label: '2 pieces (Pack of 2)', weightKg: 0.2, price: 189, mrp: 240 },
      { label: '4 pieces (Party Box)', weightKg: 0.4, price: 389, mrp: 480 },
      { label: '6 pieces (Family Box)', weightKg: 0.6, price: 589, mrp: 720 },
      { label: '12 pieces (Celebration Box)', weightKg: 1.2, price: 999, mrp: 1440 },
    ],
    images: [
      { id: 'img-6768-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Pineapple-Pastry03.webp', isPrimary: true, altText: 'Pineapple Pastry' },
    ],
    rating: 4.7,
    reviewCount: 42,
    stock: 75,
    stockStatus: 'in_stock',
    badges: ['Fresh Fruit', '100% Eggless'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6774',
    sku: 'BP',
    name: 'Butterscotch Pastry',
    slug: 'butterscotch-pastry',
    shortDescription: 'Golden sponge layered with sweet butterscotch cream and crunchy caramelized praline nuts.',
    description: '<p>Crunchy, creamy, and caramel-rich. Handcrafted with authentic praline nuts.</p>',
    category: 'desserts',
    subCategory: 'pastries',
    categories: ['desserts', 'birthday'],
    subcategories: ['pastries'],
    tags: ['Butterscotch Pastry', 'Praline Pastry', 'Pastries', 'Desserts'],
    flavours: ['Butterscotch Cream', 'Caramel Praline'],
    eggless: true,
    weightOptions: [
      { label: '1 piece', weightKg: 0.1, price: 99, mrp: 120, isDefault: true },
      { label: '2 pieces (Pack of 2)', weightKg: 0.2, price: 189, mrp: 240 },
      { label: '4 pieces (Party Box)', weightKg: 0.4, price: 389, mrp: 480 },
      { label: '6 pieces (Family Box)', weightKg: 0.6, price: 589, mrp: 720 },
      { label: '12 pieces (Celebration Box)', weightKg: 1.2, price: 999, mrp: 1440 },
    ],
    images: [
      { id: 'img-6774-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Butterscotch-Pastry01.webp', isPrimary: true, altText: 'Butterscotch Pastry' },
    ],
    rating: 4.7,
    reviewCount: 39,
    stock: 70,
    stockStatus: 'in_stock',
    badges: ['Praline Crunch', '100% Eggless'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6792',
    sku: 'RVP',
    name: 'Red Velvet Pastry',
    slug: 'red-velvet-pastry',
    shortDescription: 'Silky red velvet sponge paired with velvety cream cheese and ruby red sponge crumble.',
    description: '<p>The queen of dessert slices! Tender crimson velvet cake with rich cream cheese frosting.</p>',
    category: 'desserts',
    subCategory: 'pastries',
    categories: ['desserts', 'anniversary'],
    subcategories: ['pastries'],
    tags: ['Red Velvet Pastry', 'Cream Cheese', 'Pastries', 'Desserts'],
    flavours: ['Red Velvet', 'Cream Cheese'],
    eggless: true,
    weightOptions: [
      { label: '1 piece', weightKg: 0.1, price: 99, mrp: 120, isDefault: true },
      { label: '2 pieces (Pack of 2)', weightKg: 0.2, price: 189, mrp: 240 },
      { label: '4 pieces (Party Box)', weightKg: 0.4, price: 389, mrp: 480 },
      { label: '6 pieces (Family Box)', weightKg: 0.6, price: 589, mrp: 720 },
      { label: '12 pieces (Celebration Box)', weightKg: 1.2, price: 999, mrp: 1440 },
    ],
    images: [
      { id: 'img-6792-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Red-Velvet-Pastry01.webp', isPrimary: true, altText: 'Red Velvet Pastry' },
    ],
    rating: 4.9,
    reviewCount: 54,
    stock: 65,
    stockStatus: 'in_stock',
    badges: ['Cream Cheese', '100% Eggless'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6798',
    sku: 'BCP',
    name: 'Blueberry Cheesecake Pastry',
    slug: 'blueberry-cheesecake-pastry',
    shortDescription: 'Baked New York style cheesecake slice topped with wild Canadian blueberry compote over a buttery biscuit crust.',
    description: '<p>Silky, rich, and tangy! Handcrafted cheesecake slice with premium cream cheese and wild blueberry glaze.</p>',
    category: 'desserts',
    subCategory: 'cheesecakes',
    categories: ['desserts', 'trending-cakes'],
    subcategories: ['cheesecakes'],
    tags: ['Blueberry Cheesecake', 'Cheesecake Slice', 'New York Cheesecake', 'Desserts'],
    flavours: ['Cream Cheese', 'Wild Blueberry'],
    eggless: true,
    weightOptions: [
      { label: '1 piece', weightKg: 0.15, price: 239, mrp: 280, isDefault: true },
      { label: '2 pieces (Pack of 2)', weightKg: 0.3, price: 449, mrp: 560 },
      { label: '4 pieces (Party Box)', weightKg: 0.6, price: 889, mrp: 1120 },
      { label: '6 pieces (Family Box)', weightKg: 0.9, price: 1329, mrp: 1680 },
    ],
    images: [
      { id: 'img-6798-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Blueberry-Cheesecake-Pastry1.webp', isPrimary: true, altText: 'Blueberry Cheesecake Pastry' },
    ],
    rating: 5.0,
    reviewCount: 81,
    stock: 45,
    stockStatus: 'in_stock',
    badges: ['Gourmet Cheesecake', '100% Eggless'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6816',
    sku: 'NCS',
    name: 'Nutella Cheesecake Slice',
    slug: 'nutella-cheesecake-slice',
    shortDescription: 'Thick, creamy baked cheesecake layered with generous Nutella hazelnut chocolate spread.',
    description: '<p>A match made in dessert heaven! Smooth cream cheese marbled with decadent Nutella spread.</p>',
    category: 'desserts',
    subCategory: 'cheesecakes',
    categories: ['desserts', 'chocolate', 'trending-cakes'],
    subcategories: ['cheesecakes'],
    tags: ['Nutella Cheesecake', 'Cheesecake Slice', 'Nutella Hazelnut', 'Desserts'],
    flavours: ['Nutella Hazelnut', 'Cream Cheese'],
    eggless: true,
    weightOptions: [
      { label: '1 piece', weightKg: 0.15, price: 219, mrp: 260, isDefault: true },
      { label: '2 pieces (Pack of 2)', weightKg: 0.3, price: 419, mrp: 520 },
      { label: '4 pieces (Party Box)', weightKg: 0.6, price: 819, mrp: 1040 },
    ],
    images: [
      { id: 'img-6816-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/nutella-cheesecake-slice01.webp', isPrimary: true, altText: 'Nutella Cheesecake Slice' },
    ],
    rating: 4.9,
    reviewCount: 57,
    stock: 40,
    stockStatus: 'in_stock',
    badges: ['Nutella Love', '100% Eggless'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6839',
    sku: 'CCM',
    name: 'Coffee Chocolate Mousse',
    slug: 'coffee-chocolate-mousse',
    shortDescription: 'Aerated, cloud-like dark chocolate mousse infused with fresh espresso and dusted with cocoa.',
    description: '<p>Served in an elegant dessert cup. Airy, creamy coffee chocolate mousse with a velvety melt-in-mouth finish.</p>',
    category: 'desserts',
    subCategory: 'dessert-cups',
    categories: ['desserts', 'chocolate'],
    subcategories: ['dessert-cups'],
    tags: ['Coffee Chocolate Mousse', 'Dessert Cup', 'Mousse', 'Espresso'],
    flavours: ['Espresso Coffee', 'Dark Chocolate Mousse'],
    eggless: true,
    weightOptions: [
      { label: '1 cup', weightKg: 0.12, price: 129, mrp: 160, isDefault: true },
      { label: '2 cups (Pack of 2)', weightKg: 0.24, price: 229, mrp: 320 },
      { label: '4 cups (Party Box)', weightKg: 0.48, price: 529, mrp: 640 },
    ],
    images: [
      { id: 'img-6839-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/coffee-chocolate-mousse-cake01.webp', isPrimary: true, altText: 'Coffee Chocolate Mousse' },
    ],
    rating: 4.8,
    reviewCount: 36,
    stock: 50,
    stockStatus: 'in_stock',
    badges: ['Espresso Mousse', '100% Eggless'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6712',
    sku: 'CBLTISD',
    name: 'Classic Besan Ladoo Traditional Indian Sweet',
    slug: 'classic-besan-ladoo-traditional',
    shortDescription: 'Pure desi ghee roasted gram flour round sweet treats infused with cardamom, almonds and pistachios.',
    description: '<p>Handcrafted traditional mithai prepared using slow-roasted besan in golden pure desi ghee.</p>',
    category: 'desserts',
    subCategory: 'traditional-mithai',
    categories: ['desserts', 'hampers'],
    subcategories: ['traditional-mithai'],
    tags: ['Besan Ladoo', 'Traditional Sweets', 'Mithai', 'Desi Ghee'],
    flavours: ['Pure Desi Ghee', 'Cardamom Pistachio'],
    eggless: true,
    weightOptions: [
      { label: 'Box of 12 pcs (400g)', weightKg: 0.4, price: 599, mrp: 699, isDefault: true },
      { label: 'Pack of 200g', weightKg: 0.2, price: 299, mrp: 349 },
    ],
    images: [
      { id: 'img-6712-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/08/classic-besan-ladoo-traditional-indian-sweet-delight-1.png', isPrimary: true, altText: 'Classic Besan Ladoo' },
    ],
    rating: 4.9,
    reviewCount: 71,
    stock: 60,
    stockStatus: 'in_stock',
    badges: ['Pure Desi Ghee', 'Traditional Delight'],
    published: true,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prod-7453',
    sku: 'CFCC75G',
    name: 'Center Filled Choco-Cookies 75g',
    slug: 'center-filled-choco-cookies-75g',
    shortDescription: 'Crunchy cocoa butter cookies with a gooey, molten chocolate lava core inside every cookie.',
    description: '<p>Bite into a crunchy outer crust to reveal molten Belgian chocolate ganache filling.</p>',
    category: 'desserts',
    subCategory: 'cookies',
    categories: ['desserts', 'chocolate'],
    subcategories: ['cookies'],
    tags: ['Choco Cookies', 'Center Filled Cookies', 'Lava Cookies', 'Bakery'],
    flavours: ['Molten Chocolate', 'Crisp Butter Cookie'],
    eggless: true,
    weightOptions: [
      { label: 'Pack of 75g', weightKg: 0.075, price: 299, mrp: 399, isDefault: true },
      { label: 'Pack of 2 (150g)', weightKg: 0.15, price: 499, mrp: 699 },
    ],
    images: [
      { id: 'img-7453-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/07/Center-Filled-Choco-Cookies-75g.png', isPrimary: true, altText: 'Center Filled Choco Cookies' },
    ],
    rating: 4.8,
    reviewCount: 28,
    stock: 90,
    stockStatus: 'in_stock',
    badges: ['Molten Core', 'Eggless'],
    published: true,
    createdAt: '2026-07-15T10:00:00Z',
    updatedAt: '2026-07-15T10:00:00Z',
  },
];
