import { Product } from '../types';

export const CSV_HAMPER_PRODUCTS: Product[] = [
  {
    id: 'prod-6705',
    sku: 'GBDH',
    name: 'Golden Bliss Diwali Hamper',
    slug: 'golden-bliss-diwali-hamper',
    shortDescription: 'Luxe festive gift hamper with gourmet dry fruits, artisanal sweet bites, terracotta diyas, and celebratory treats in a gold-embossed keepsake box.',
    description: '<p>Illuminate celebrations with our <strong>Golden Bliss Diwali Hamper</strong>. Filled with premium roasted dry fruits, festive sweets, decorative diyas, and celebratory greeting card.</p>',
    category: 'hampers',
    subCategory: 'diwali-gift-hampers',
    categories: ['hampers'],
    subcategories: ['diwali-gift-hampers', 'festival-hampers'],
    tags: ['Diwali Hamper', 'Gift Hamper', 'Dry Fruits', 'Festival Hamper', 'Diwali Gifts'],
    flavours: ['Dry Fruits & Sweets'],
    eggless: true,
    weightOptions: [
      { label: 'Royal Hamper Box (1.0 kg)', weightKg: 1.0, price: 999, mrp: 1299, isDefault: true },
    ],
    images: [
      { id: 'img-6705-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Golden-Bliss-Diwali-Hamper.png', isPrimary: true, altText: 'Golden Bliss Diwali Hamper' },
    ],
    rating: 5.0,
    reviewCount: 48,
    stock: 60,
    stockStatus: 'in_stock',
    badges: ['Diwali Bestseller', 'Luxe Box'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6706',
    sku: 'AGDF',
    name: 'Assorted Gourmet Dry Fruits Box',
    slug: 'assorted-gourmet-dry-fruits',
    shortDescription: 'Premium selection of California almonds, whole cashews, Afghani raisins, and salted pistachios in an airtight partition box.',
    description: '<p>A classic and wholesome festive gift box loaded with high-grade handpicked nuts and dried fruits.</p>',
    category: 'hampers',
    subCategory: 'dry-fruit-boxes',
    categories: ['hampers'],
    subcategories: ['dry-fruit-boxes', 'diwali-gift-hampers'],
    tags: ['Dry Fruit Box', 'Assorted Nuts', 'Diwali Hamper', 'Healthy Gifting'],
    flavours: ['Roasted Almonds, Cashews, Pistachios, Raisins'],
    eggless: true,
    weightOptions: [
      { label: 'Gourmet Box (400g)', weightKg: 0.4, price: 999, mrp: 1299, isDefault: true },
    ],
    images: [
      { id: 'img-6706-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Assorted-Gourmet-Dry-Fruits.png', isPrimary: true, altText: 'Assorted Gourmet Dry Fruits' },
    ],
    rating: 4.9,
    reviewCount: 37,
    stock: 50,
    stockStatus: 'in_stock',
    badges: ['Healthy Gifting', 'Premium Nuts'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6707',
    sku: 'EDTBPCGDF',
    name: 'Elegant Diwali Treat Box Potli, Cookies & Gourmet Dry Fruits',
    slug: 'elegant-diwali-treat-box-potli-cookies',
    shortDescription: 'Festive hamper featuring silk brocade potlis, handmade bakery cookies, assorted dry fruits, and brass scented tealights.',
    description: '<p>Traditional charm meets modern luxury with this handcrafted Diwali gift hamper box.</p>',
    category: 'hampers',
    subCategory: 'festival-hampers',
    categories: ['hampers'],
    subcategories: ['festival-hampers', 'diwali-gift-hampers'],
    tags: ['Potli Hamper', 'Diwali Treat Box', 'Cookies & Dry Fruits', 'Diwali Gifts'],
    flavours: ['Cookies & Roasted Nuts'],
    eggless: true,
    weightOptions: [
      { label: 'Festive Treat Box', weightKg: 0.8, price: 999, mrp: 1299, isDefault: true },
    ],
    images: [
      { id: 'img-6707-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Elegant-Diwali-Treat-Box-Potli-Cookies-Gourmet-Dry-Fruits.png', isPrimary: true, altText: 'Elegant Diwali Treat Box' },
    ],
    rating: 4.8,
    reviewCount: 29,
    stock: 40,
    stockStatus: 'in_stock',
    badges: ['Festive Potli', 'Gift Ready'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6708',
    sku: 'CCDB',
    name: 'Custom Corporate Delight Box',
    slug: 'custom-corporate-delight-box',
    shortDescription: 'Curated corporate gifting set with premium treats, coasters, roasted snack mix, and branded gift card.',
    description: '<p>The ideal choice for client appreciation, employee festive rewards, and executive gifting.</p>',
    category: 'hampers',
    subCategory: 'corporate-hampers',
    categories: ['hampers'],
    subcategories: ['corporate-hampers', 'diwali-gift-hampers'],
    tags: ['Corporate Gifting', 'Diwali Hampers', 'Executive Gift Box'],
    flavours: ['Gourmet Snacks & Sweets'],
    eggless: true,
    weightOptions: [
      { label: 'Executive Gift Box', weightKg: 1.0, price: 1199, mrp: 1499, isDefault: true },
    ],
    images: [
      { id: 'img-6708-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Custom-Corporate-Delight-Box.png', isPrimary: true, altText: 'Custom Corporate Delight Box' },
    ],
    rating: 4.9,
    reviewCount: 34,
    stock: 50,
    stockStatus: 'in_stock',
    badges: ['Corporate Favorite', 'Bulk Discounts'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6713',
    sku: 'FFDFCBDGT',
    name: 'Festive Fusion Dry Fruit Chocolate Barfi Diwali Gift Tray',
    slug: 'festive-fusion-dry-fruit-chocolate-barfi-tray',
    shortDescription: 'Modern mithai fusion tray of dark chocolate coated kaju barfi topped with toasted almond flakes and silver vark.',
    description: '<p>An exquisite culinary blend of traditional Indian mawa barfi and Belgian dark chocolate coating.</p>',
    category: 'hampers',
    subCategory: 'festival-hampers',
    categories: ['hampers', 'desserts'],
    subcategories: ['festival-hampers', 'traditional-mithai'],
    tags: ['Chocolate Barfi', 'Dry Fruit Tray', 'Diwali Mithai', 'Fusion Sweet'],
    flavours: ['Chocolate Kaju Barfi'],
    eggless: true,
    weightOptions: [
      { label: 'Gift Tray (500g)', weightKg: 0.5, price: 899, mrp: 1099, isDefault: true },
    ],
    images: [
      { id: 'img-6713-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/08/festive-fusion-dry-fruit-chocolate-barfi-diwali-gift-tray-1.png', isPrimary: true, altText: 'Festive Fusion Barfi Tray' },
    ],
    rating: 4.9,
    reviewCount: 45,
    stock: 45,
    stockStatus: 'in_stock',
    badges: ['Fusion Mithai', 'Silver Vark'],
    published: true,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prod-6714',
    sku: 'RDFDGBVE',
    name: 'Royal Dry Fruit Diwali Gift Box Velvet Edition',
    slug: 'royal-dry-fruit-diwali-gift-box-velvet',
    shortDescription: 'Plush velvet exterior drawer box loaded with jumbo cashews, mamra badam, Turkish figs, and golden raisins.',
    description: '<p>A regal presentation for the most prestigious Diwali blessings and family gifts.</p>',
    category: 'hampers',
    subCategory: 'dry-fruit-boxes',
    categories: ['hampers'],
    subcategories: ['dry-fruit-boxes', 'diwali-gift-hampers'],
    tags: ['Velvet Box', 'Royal Dry Fruits', 'Diwali Luxe', 'Mamra Badam'],
    flavours: ['Royal Jumbo Dry Fruits'],
    eggless: true,
    weightOptions: [
      { label: 'Velvet Edition Box (800g)', weightKg: 0.8, price: 1599, mrp: 1999, isDefault: true },
    ],
    images: [
      { id: 'img-6714-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/08/royal-dry-fruit-diwali-gift-box-velvet-edition-1.png', isPrimary: true, altText: 'Royal Dry Fruit Velvet Box' },
    ],
    rating: 5.0,
    reviewCount: 38,
    stock: 35,
    stockStatus: 'in_stock',
    badges: ['Velvet Edition', 'Luxury'],
    published: true,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prod-6719',
    sku: 'DCHLB',
    name: 'Diwali Candle Hamper of Light & Blessings',
    slug: 'diwali-candle-hamper-light-blessings',
    shortDescription: 'Includes scented glass candles, decorative brass diyas, organic incense cones, and sweets in an illuminated gift box.',
    description: '<p>Spread warmth and divine energy with our aromatherapy candle and blessing set.</p>',
    category: 'festive-candles',
    subCategory: 'pillar-candles',
    categories: ['festive-candles', 'hampers'],
    subcategories: ['pillar-candles', 'festival-hampers'],
    tags: ['Diwali Candle Hamper', 'Scented Candle', 'Diwali Decor', 'Aromatherapy'],
    flavours: ['Sandalwood & Jasmine Aroma'],
    eggless: true,
    weightOptions: [
      { label: 'Blessing Hamper Set', weightKg: 1.2, price: 1899, mrp: 2299, isDefault: true },
    ],
    images: [
      { id: 'img-6719-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Diwali-Candle-Hamper-of-Light-Blessings.png', isPrimary: true, altText: 'Diwali Candle Hamper' },
    ],
    rating: 5.0,
    reviewCount: 51,
    stock: 30,
    stockStatus: 'in_stock',
    badges: ['Divine Light', 'Aromatherapy'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6724',
    sku: 'SJCS3',
    name: 'Scented Jar Candle Set of 3',
    slug: 'scented-jar-candle-set-of-3',
    shortDescription: 'Set of 3 hand-poured soy wax candles with Vanilla, Lavender, and Rose aromas in frosted glass jars.',
    description: '<p>Long-burning natural soy wax candles designed to fill your home with relaxing floral fragrance.</p>',
    category: 'festive-candles',
    subCategory: 'scented-jar-candles',
    categories: ['festive-candles'],
    subcategories: ['scented-jar-candles'],
    tags: ['Scented Candles', 'Jar Candles', 'Soy Wax', 'Home Decor'],
    flavours: ['Vanilla, Lavender, Rose Aroma'],
    eggless: true,
    weightOptions: [
      { label: 'Set of 3 Jars', weightKg: 0.6, price: 899, mrp: 1199, isDefault: true },
    ],
    images: [
      { id: 'img-6724-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Scented-Jar-Candle-Set-of-3.png', isPrimary: true, altText: 'Scented Jar Candle Set' },
    ],
    rating: 4.8,
    reviewCount: 33,
    stock: 45,
    stockStatus: 'in_stock',
    badges: ['100% Soy Wax', 'Aroma Decor'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'prod-6757',
    sku: 'TGLI',
    name: 'Traditional Ganesh Laxmi Idols',
    slug: 'traditional-ganesh-laxmi-idols',
    shortDescription: 'Hand-painted terracotta Lakshmi and Ganesha deities for Diwali Pooja and auspicious home blessings.',
    description: '<p>Divine sacred idols crafted by skilled artisans for Diwali Pooja, Griha Pravesh, and gift hampers.</p>',
    category: 'festive-candles',
    subCategory: 'pooja-idols',
    categories: ['festive-candles', 'hampers'],
    subcategories: ['pooja-idols'],
    tags: ['Ganesh Laxmi Idols', 'Pooja Essentials', 'Diwali Pooja', 'Handcrafted Idols'],
    flavours: ['Sacred Pooja Essentials'],
    eggless: true,
    weightOptions: [
      { label: 'Pair of Idols (Height 4 inch)', weightKg: 0.5, price: 599, mrp: 799, isDefault: true },
    ],
    images: [
      { id: 'img-6757-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/05/Traditional-Ganesh-Laxmi-Idols.png', isPrimary: true, altText: 'Traditional Ganesh Laxmi Idols' },
    ],
    rating: 5.0,
    reviewCount: 62,
    stock: 50,
    stockStatus: 'in_stock',
    badges: ['Pooja Essential', 'Handmade'],
    published: true,
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
];
