import { Product } from '../types';

export const CSV_RAKHI_PRODUCTS: Product[] = [
  {
    id: 'prod-7445',
    sku: 'CPRDT',
    name: 'Colourful Peacock Rakhis With Delightful Treats',
    slug: 'colourful-peacock-rakhis-with-treats',
    shortDescription: 'Exquisite meenakari peacock rakhis paired with gourmet sweets, roasted dry fruits, and roli chawal in a festive gift box.',
    description: '<p>Celebrate the divine bond of sibling love with our handcrafted peacock rakhis and sweet festive treats.</p>',
    category: 'rakhi-hampers',
    subCategory: 'raksha-bandhan-hampers',
    categories: ['rakhi-hampers'],
    subcategories: ['raksha-bandhan-hampers', 'rakhi-sets'],
    tags: ['Peacock Rakhi', 'Rakhi Hamper', 'Raksha Bandhan', 'Sweets & Rakhi'],
    flavours: ['Sweets & Roasted Dry Fruits'],
    eggless: true,
    weightOptions: [
      { label: 'Complete Hamper Box', weightKg: 1.0, price: 1899, mrp: 2199, isDefault: true },
    ],
    images: [
      { id: 'img-7445-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/07/Colourful-Peacock-Rakhis-With-Delightful-Treats.png', isPrimary: true, altText: 'Peacock Rakhi Hamper' },
    ],
    rating: 5.0,
    reviewCount: 47,
    stock: 50,
    stockStatus: 'in_stock',
    badges: ['Bestseller Rakhi', 'Meenakari Art'],
    published: true,
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'prod-7450',
    sku: 'SBBRSH',
    name: 'Sacred Bhaiya Bhabhi Rakhi And Sweets Hamper',
    slug: 'sacred-bhaiya-bhabhi-rakhi-sweets-hamper',
    shortDescription: 'Matching Bhaiya-Bhabhi lumba rakhi set paired with traditional kaju katli and desi ghee ladoos.',
    description: '<p>A complete festive package designed specifically for your beloved Bhaiya and Bhabhi.</p>',
    category: 'rakhi-hampers',
    subCategory: 'bhaiya-bhabhi-rakhi',
    categories: ['rakhi-hampers'],
    subcategories: ['bhaiya-bhabhi-rakhi', 'raksha-bandhan-hampers'],
    tags: ['Bhaiya Bhabhi Rakhi', 'Lumba Rakhi', 'Rakhi Sweets', 'Raksha Bandhan'],
    flavours: ['Kaju Katli & Besan Ladoo'],
    eggless: true,
    weightOptions: [
      { label: 'Bhaiya Bhabhi Set Box', weightKg: 0.6, price: 899, mrp: 1099, isDefault: true },
    ],
    images: [
      { id: 'img-7450-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/07/Sacred-Bhaiya-Bhabhi-Rakhi-And-Sweets-Hamper.png', isPrimary: true, altText: 'Bhaiya Bhabhi Rakhi Hamper' },
    ],
    rating: 4.9,
    reviewCount: 52,
    stock: 45,
    stockStatus: 'in_stock',
    badges: ['Lumba Set', 'Traditional Sweets'],
    published: true,
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'prod-7443',
    sku: 'SERS2',
    name: 'Space Explorer Rakhi Set Of 2',
    slug: 'space-explorer-rakhi-set-2',
    shortDescription: 'Fun glow-in-the-dark rocket and astronaut silicone bands designed for younger brothers and kids.',
    description: '<p>Delight little astronauts with these fun, skin-safe silicone space explorer rakhis.</p>',
    category: 'rakhi-hampers',
    subCategory: 'kids-rakhi-boxes',
    categories: ['rakhi-hampers'],
    subcategories: ['kids-rakhi-boxes', 'rakhi-sets'],
    tags: ['Kids Rakhi', 'Space Rakhi', 'Cartoon Rakhi', 'Astronaut'],
    flavours: ['Kids Fun Theme'],
    eggless: true,
    weightOptions: [
      { label: 'Set of 2 Rakhis', weightKg: 0.05, price: 199, mrp: 249, isDefault: true },
    ],
    images: [
      { id: 'img-7443-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/07/Space-Explorer-Rakhi-Set-Of-2.png', isPrimary: true, altText: 'Space Explorer Rakhi Set' },
    ],
    rating: 4.8,
    reviewCount: 39,
    stock: 80,
    stockStatus: 'in_stock',
    badges: ['Kids Special', 'Glow in Dark'],
    published: true,
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'prod-7897',
    sku: 'RH-MINI',
    name: 'Mini Rakhi Box',
    slug: 'mini-rakhi-box',
    shortDescription: 'Compact pocket-friendly gift box featuring 1 handcrafted rakhi, mini chocolate box, and roli-chawal.',
    description: '<p>Affordable yet delightful festive gesture packed in an elegant presentation box.</p>',
    category: 'rakhi-hampers',
    subCategory: 'budget-rakhi-boxes',
    categories: ['rakhi-hampers'],
    subcategories: ['budget-rakhi-boxes'],
    tags: ['Mini Rakhi Box', 'Budget Rakhi', 'Chocolate Rakhi Box'],
    flavours: ['Mini Chocolates'],
    eggless: true,
    weightOptions: [
      { label: 'Mini Festive Box', weightKg: 0.25, price: 399, mrp: 499, isDefault: true },
    ],
    images: [
      { id: 'img-7897-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/07/Mini-Rakhi-Box.png', isPrimary: true, altText: 'Mini Rakhi Box' },
    ],
    rating: 4.7,
    reviewCount: 63,
    stock: 90,
    stockStatus: 'in_stock',
    badges: ['Budget Friendly', 'Express Delivery'],
    published: true,
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'prod-7902',
    sku: 'RH-CHOCOHEAVEN',
    name: 'Chocolate Heaven Hamper',
    slug: 'chocolate-heaven-hamper',
    shortDescription: 'Assorted handmade chocolate bars, hazelnut truffles, brownie bites, and designer thread rakhi.',
    description: '<p>A paradise for chocolate lovers! Curated artisan chocolates and brownies for Rakhi celebration.</p>',
    category: 'rakhi-hampers',
    subCategory: 'bakery-rakhi-boxes',
    categories: ['rakhi-hampers', 'chocolate'],
    subcategories: ['bakery-rakhi-boxes'],
    tags: ['Chocolate Heaven Hamper', 'Rakhi Chocolates', 'Brownie Hamper'],
    flavours: ['Artisan Chocolates & Brownies'],
    eggless: true,
    weightOptions: [
      { label: 'Heaven Box (600g)', weightKg: 0.6, price: 999, mrp: 1299, isDefault: true },
    ],
    images: [
      { id: 'img-7902-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/07/Chocolate-Heaven-Hamper.png', isPrimary: true, altText: 'Chocolate Heaven Hamper' },
    ],
    rating: 4.9,
    reviewCount: 44,
    stock: 55,
    stockStatus: 'in_stock',
    badges: ['Chocolate Lover', 'Eggless'],
    published: true,
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'prod-7906',
    sku: 'RH-LUXURY',
    name: 'Luxury Rakhi Hamper',
    slug: 'luxury-rakhi-hamper',
    shortDescription: 'Grand multi-tiered celebration hamper with silver plated rakhi, luxury sweets, dry fruits, and gourmet bakery jar cakes.',
    description: '<p>The ultimate royal expression of sisterly love and sibling joy for Raksha Bandhan.</p>',
    category: 'rakhi-hampers',
    subCategory: 'luxury-rakhi-hampers',
    categories: ['rakhi-hampers'],
    subcategories: ['luxury-rakhi-hampers'],
    tags: ['Luxury Rakhi Hamper', 'Silver Plated Rakhi', 'Grand Hamper', 'Raksha Bandhan'],
    flavours: ['Royal Dry Fruits & Jar Cakes'],
    eggless: true,
    weightOptions: [
      { label: 'Grand Multi-Tier Box (1.5 kg)', weightKg: 1.5, price: 2499, mrp: 2999, isDefault: true },
    ],
    images: [
      { id: 'img-7906-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/07/Luxury-Rakhi-Hamper.png', isPrimary: true, altText: 'Luxury Rakhi Hamper' },
    ],
    rating: 5.0,
    reviewCount: 38,
    stock: 25,
    stockStatus: 'in_stock',
    badges: ['Signature Luxury', 'Silver Rakhi'],
    published: true,
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'prod-8262',
    sku: 'RH01',
    name: 'Sweet Bond Box',
    slug: 'sweet-bond-box',
    shortDescription: 'Handcrafted rakhi thread with fresh homemade milk pedas in an eco-friendly gift sleeve.',
    description: '<p>A classic sweet bond gift box delivering pure love and traditional sweetness.</p>',
    category: 'rakhi-hampers',
    subCategory: 'budget-rakhi-boxes',
    categories: ['rakhi-hampers'],
    subcategories: ['budget-rakhi-boxes'],
    tags: ['Sweet Bond Box', 'Budget Rakhi', 'Rakhi Sweets'],
    flavours: ['Milk Pedas & Rakhi'],
    eggless: true,
    weightOptions: [
      { label: 'Sweet Bond Box', weightKg: 0.2, price: 199, mrp: 249, isDefault: true },
    ],
    images: [
      { id: 'img-8262-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/08/Sweet-Bond-Box.png', isPrimary: true, altText: 'Sweet Bond Box' },
    ],
    rating: 4.8,
    reviewCount: 31,
    stock: 100,
    stockStatus: 'in_stock',
    badges: ['Only ₹199', 'Fast Delivery'],
    published: true,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'prod-8263',
    sku: 'RH02',
    name: 'Chocolate Love Box',
    slug: 'chocolate-love-box',
    shortDescription: 'Assortment of handmade dark and milk chocolate pralines with a beaded designer rakhi.',
    description: '<p>Sweeten your sibling bond with exquisite dark chocolate pralines and designer rakhi.</p>',
    category: 'rakhi-hampers',
    subCategory: 'budget-rakhi-boxes',
    categories: ['rakhi-hampers', 'chocolate'],
    subcategories: ['budget-rakhi-boxes'],
    tags: ['Chocolate Love Box', 'Rakhi Chocolates', 'Beaded Rakhi'],
    flavours: ['Assorted Pralines'],
    eggless: true,
    weightOptions: [
      { label: 'Love Box (250g)', weightKg: 0.25, price: 399, mrp: 499, isDefault: true },
    ],
    images: [
      { id: 'img-8263-1', url: 'https://tvoflavours.com/wp-content/uploads/2026/08/Love-Box.png', isPrimary: true, altText: 'Chocolate Love Box' },
    ],
    rating: 4.9,
    reviewCount: 40,
    stock: 75,
    stockStatus: 'in_stock',
    badges: ['Popular', 'Eggless'],
    published: true,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-01T10:00:00Z',
  },
];
