import { Category } from './types';

export const CSV_CATEGORIES: Category[] = [
  {
    id: 'cat-birthday',
    name: 'Birthday Cakes',
    slug: 'birthday',
    description: 'Delectable handcrafted birthday cakes for kids, adults, and grand milestones.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/05/Choco-Chip-Truffle-Cake.png',
    featured: true,
    itemCount: 24,
    subcategories: [
      { id: 'sub-bday-kids', name: "Kids' Cakes", slug: 'kids-cakes' },
      { id: 'sub-bday-photo', name: 'Photo Cakes', slug: 'photo-cakes' },
      { id: 'sub-bday-truffle', name: 'Truffle & Ganache', slug: 'chocolate' },
      { id: 'sub-bday-butterscotch', name: 'Butterscotch & Crunch', slug: 'butterscotch' },
    ],
  },
  {
    id: 'cat-anniversary',
    name: 'Anniversary Cakes',
    slug: 'anniversary',
    description: 'Romantic heart-shaped, tiered, and red velvet cakes to celebrate enduring love.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/05/Hearts-Of-Love-Chocolate-Cake.png',
    featured: true,
    itemCount: 18,
    subcategories: [
      { id: 'sub-anni-heart', name: 'Heart Shaped', slug: 'heart-shaped' },
      { id: 'sub-anni-redvelvet', name: 'Red Velvet', slug: 'red-velvet' },
      { id: 'sub-anni-tiered', name: '2-Tier & Tiered', slug: 'tiered-cakes' },
    ],
  },
  {
    id: 'cat-chocolate',
    name: 'Chocolate Overload',
    slug: 'chocolate',
    description: 'Indulgent Belgian dark truffle, KitKat overload, Nutella, and molten chocolate cakes.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/05/Belgian-Chocolate-Cake.png',
    featured: true,
    itemCount: 30,
    subcategories: [
      { id: 'sub-choco-truffle', name: 'Dark Truffle', slug: 'dark-truffle' },
      { id: 'sub-choco-belgian', name: 'Belgian Pure Cocoa', slug: 'belgian-chocolate' },
      { id: 'sub-choco-kitkat', name: 'KitKat & Ferrero', slug: 'kitkat-ferrero' },
    ],
  },
  {
    id: 'cat-mango',
    name: 'Mango Specials',
    slug: 'mango-cakes',
    description: 'Luscious seasonal Alphonso mango cream cakes and fresh fruit glazes.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/08/Classic-Mango-cream-cake.png',
    featured: true,
    itemCount: 12,
    subcategories: [
      { id: 'sub-mango-alphonso', name: 'Alphonso Cream', slug: 'alphonso-mango' },
      { id: 'sub-mango-gateau', name: 'Mango Gateau', slug: 'mango-gateau' },
    ],
  },
  {
    id: 'cat-fruit',
    name: 'Fresh Fruit Cakes',
    slug: 'fruit-cakes',
    description: 'Loaded with farm-fresh seasonal fruits, light vanilla sponge, and dairy whipped cream.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/05/Pineapple-Cake.png',
    featured: true,
    itemCount: 16,
    subcategories: [
      { id: 'sub-fruit-pineapple', name: 'Classic Pineapple', slug: 'pineapple' },
      { id: 'sub-fruit-mix', name: 'Exotic Mixed Fruit', slug: 'mixed-fruit' },
      { id: 'sub-fruit-berry', name: 'Wild Berry', slug: 'berry-cakes' },
    ],
  },
  {
    id: 'cat-trending',
    name: 'Trending & Dubai Kunafa',
    slug: 'trending-cakes',
    description: 'Viral pistachio kunafa chocolate cakes, pinata smash cakes, and pull-me-up sensations.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/05/Kunafa-Dubai-Cake.png',
    featured: true,
    itemCount: 14,
    subcategories: [
      { id: 'sub-trend-kunafa', name: 'Dubai Pistachio Kunafa', slug: 'dubai-kunafa' },
      { id: 'sub-trend-pinata', name: 'Pinata Smash Cakes', slug: 'pinata-cakes' },
      { id: 'sub-trend-pullmeup', name: 'Pull Me Up Cakes', slug: 'pull-me-up' },
    ],
  },
  {
    id: 'cat-eggless',
    name: '100% Eggless Gourmet',
    slug: 'eggless',
    description: 'All-inclusive, 100% vegetarian artisan bakes crafted with the fluffiest sponge.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/05/Eggless-Tiramisu-Cake.png',
    featured: true,
    itemCount: 45,
    subcategories: [
      { id: 'sub-eggless-tiramisu', name: 'Eggless Tiramisu', slug: 'tiramisu' },
      { id: 'sub-eggless-cheesecake', name: 'Eggless Cheesecakes', slug: 'cheesecakes' },
    ],
  },
  {
    id: 'cat-desserts',
    name: 'Desserts & Pastries',
    slug: 'desserts',
    description: 'Individual pastry slices, cheesecake cuts, dessert cups, cookies, and traditional Indian sweets.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/05/Blueberry-Cheesecake-Pastry1.webp',
    featured: true,
    itemCount: 22,
    subcategories: [
      { id: 'sub-des-pastries', name: 'Pastry Slices', slug: 'pastries' },
      { id: 'sub-des-cheesecake', name: 'Cheesecake Slices', slug: 'cheesecakes' },
      { id: 'sub-des-cups', name: 'Mousse & Dessert Cups', slug: 'dessert-cups' },
      { id: 'sub-des-mithai', name: 'Traditional Mithai', slug: 'traditional-mithai' },
      { id: 'sub-des-cookies', name: 'Artisan Cookies', slug: 'cookies' },
    ],
  },
  {
    id: 'cat-hampers',
    name: 'Gift Hampers & Dry Fruits',
    slug: 'hampers',
    description: 'Curated corporate and festive gift hampers loaded with premium dry fruits, sweets, and candles.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/05/Golden-Bliss-Diwali-Hamper.png',
    featured: true,
    itemCount: 15,
    subcategories: [
      { id: 'sub-ham-diwali', name: 'Diwali Gift Hampers', slug: 'diwali-gift-hampers' },
      { id: 'sub-ham-dryfruits', name: 'Gourmet Dry Fruit Boxes', slug: 'dry-fruit-boxes' },
      { id: 'sub-ham-corp', name: 'Corporate Hampers', slug: 'corporate-hampers' },
      { id: 'sub-ham-fest', name: 'Festival Treat Boxes', slug: 'festival-hampers' },
    ],
  },
  {
    id: 'cat-rakhi',
    name: 'Rakhi & Festive Sets',
    slug: 'rakhi-hampers',
    description: 'Handmade rakhi thread sets, Bhaiya-Bhabhi lumbas, sweets combos, and kids explorer sets.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/07/Colourful-Peacock-Rakhis-With-Delightful-Treats.png',
    featured: true,
    itemCount: 16,
    subcategories: [
      { id: 'sub-rak-sets', name: 'Designer Rakhi Sets', slug: 'raksha-bandhan-hampers' },
      { id: 'sub-rak-bb', name: 'Bhaiya Bhabhi Sets', slug: 'bhaiya-bhabhi-rakhi' },
      { id: 'sub-rak-kids', name: 'Kids Special Rakhis', slug: 'kids-rakhi-boxes' },
      { id: 'sub-rak-budget', name: 'Pocket Friendly Boxes', slug: 'budget-rakhi-boxes' },
      { id: 'sub-rak-luxe', name: 'Luxury Hampers', slug: 'luxury-rakhi-hampers' },
    ],
  },
  {
    id: 'cat-candles',
    name: 'Festive Candles & Pooja',
    slug: 'festive-candles',
    description: 'Soy wax scented jars, brass diyas, and auspicious Lakshmi-Ganesh pooja idols.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/05/Diwali-Candle-Hamper-of-Light-Blessings.png',
    featured: false,
    itemCount: 8,
    subcategories: [
      { id: 'sub-can-scented', name: 'Scented Glass Jars', slug: 'scented-jar-candles' },
      { id: 'sub-can-pooja', name: 'Pooja Idols & Brass', slug: 'pooja-idols' },
      { id: 'sub-can-pillar', name: 'Pillar Candle Sets', slug: 'pillar-candles' },
    ],
  },
  {
    id: 'cat-relation',
    name: 'Cakes By Relation',
    slug: 'by-relation',
    description: 'Special celebration designs curated for Mom, Dad, Brother, Sister, Boss, and Sweetheart.',
    image: 'https://tvoflavours.com/wp-content/uploads/2026/05/Best-Mom-Ever-Chocolate-Cake.png',
    featured: false,
    itemCount: 12,
    subcategories: [
      { id: 'sub-rel-mom', name: 'For Mother', slug: 'for-mother' },
      { id: 'sub-rel-dad', name: 'For Father', slug: 'for-father' },
      { id: 'sub-rel-partner', name: 'For Husband/Wife', slug: 'for-partner' },
    ],
  },
];
